### ISSUE TITLE
1.1 As an operator I want to register my restaurant so that I can use the app

### ISSUE THREAD

**Issue by reuseman** [reuseman/GoOutSafe#4]
1.1 As an operator I want to register my restaurant so that I can use the app

**Comment by reuseman** [comment]
Refactor endpoint in/register/operator

**Comment by reuseman** [comment]
Check test coverage at 100% both for:
- unit test
- unit component

Move the single tests in tests/test_unit and test/test_component folders

**Comment by apuccia** [comment]
Refactor endpoints in:
/operator/myrestaurants
/restaurants/new
/restaurants/<rest_id>/tables/new
/restaurants/<rest_id>/menus/new
/restaurants/<rest_id>/menus/show/<menu_id>
/restaurants/<rest_id>/tables/edit/<table_id>
/restaurants/<rest_id>/tables/delete/<table_id>
